# Generated by Django 2.1.15 on 2020-08-08 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locname', models.CharField(max_length=60)),
                ('Department', models.CharField(blank=True, max_length=60, null=True)),
                ('address1', models.CharField(max_length=300)),
                ('address2', models.CharField(max_length=300)),
                ('suburb', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=300)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='locationtimings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=60)),
                ('availability', models.BooleanField(default=False)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='location.location')),
                ('dayOfTheWeek', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
