# Generated by Django 2.1.15 on 2020-08-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='locid',
            field=models.IntegerField(default=31212),
            preserve_default=False,
        ),
    ]
