# Generated by Django 2.1.15 on 2020-09-02 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_location_locid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='Department',
            new_name='department',
        ),
    ]
