# Generated by Django 2.1.15 on 2020-08-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20200613_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(default='k@k.com', max_length=60, null=True),
        ),
    ]
