# Generated by Django 2.1.15 on 2020-08-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20200823_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='address2',
            field=models.TextField(null=True),
        ),
    ]
