# Generated by Django 2.1.15 on 2020-08-23 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20200823_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='employeeavailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=60)),
                ('availability', models.BooleanField(default=False)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='employee.employee')),
                ('dayOfTheWeek', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='certifications',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='contracthours',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='deparment',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employeetype',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Casual', 'Casual')], max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
