# Generated by Django 2.1.15 on 2020-09-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20200823_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='deparment',
            new_name='department',
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='zip',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
