# Generated by Django 2.1.15 on 2020-09-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20200902_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='certifications',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeetype',
            field=models.CharField(choices=[('FT', 'FT'), ('Part Time', 'PT'), ('Casual', 'C')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
