# Generated by Django 2.1.15 on 2020-09-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_auto_20200902_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeetype',
            field=models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('C', 'Casual')], max_length=60, null=True),
        ),
    ]
