# Generated by Django 2.1.15 on 2020-06-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('descritption', models.CharField(max_length=180)),
                ('skill', models.CharField(max_length=60, null=True)),
                ('certification', models.CharField(max_length=60, null=True)),
            ],
        ),
    ]
