# Generated by Django 2.1.15 on 2020-06-17 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='roles',
            new_name='role',
        ),
    ]
