# Generated by Django 2.1.15 on 2020-06-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_auto_20200617_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='descritption',
            field=models.CharField(max_length=180, null=True),
        ),
    ]
