# Generated by Django 2.1.15 on 2020-06-17 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_auto_20200617_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='descritption',
            new_name='description',
        ),
    ]
