# Generated by Django 2.1.15 on 2020-07-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_auto_20200617_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='certification',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='skill',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
