# Generated by Django 2.1.15 on 2020-07-15 10:24

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenttimings',
            name='endTime',
            field=models.TimeField(default=datetime.time(16, 00)),
            preserve_default=False,
        ),
    ]
