# Generated by Django 2.1.15 on 2020-07-22 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_departmenttimings_endtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='skill',
            new_name='role',
        ),
    ]
