# Generated by Django 2.1.15 on 2020-07-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_auto_20200722_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmenttimings',
            old_name='weekday',
            new_name='day',
        ),
        migrations.AddField(
            model_name='departmenttimings',
            name='availability',
            field=models.BooleanField(default=False),
        ),
    ]
