# Generated by Django 2.1.15 on 2020-08-08 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_departmenttimings_dayoftheweek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmenttimings',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='departments.department'),
        ),
    ]
